config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :post
  root "post#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
    validates :title, presence: true
    validates :body, presence: true 
    validate :validate_image 

    private def validate_image 
        if image.attached? && !image.content_type.in?(%w[image/jpeg image/png])
            errors.add(:image, 'must be a JPEG or PNG')
        elsif image.attached? == false 
            errors.add(:image, 'must be attached')
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/post_controller.rb
class PostController < ApplicationController

    def index
        @post = Post.all
    end

    def new
        @post = Post.new
    end

    def create 
        @post = Post.new(post_params)
        if @post.save
            redirect_to root_path
        else 
            render :plain => @post.errors.inspect
        end
    end

    def show 
        @post = Post.find(params[:id])
        
        if @post.image == nil
            @post.image = "https://www.w3schools.com/w3css/img_avatar3.png"
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to root_path
        else
            render :plain => @post.errors.inspect
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to root_path, :notice => "Post deleted"
    end

    private def post_params 
        params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item text-end">
        <%= link_to "Create Post", new_post_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <title>Hello, world!</title>
  </head>
  <body>
    <%= yield %>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/post/edit.html.erb
<%= render "layouts/navbar" %>

<div class="container">
<%= simple_form_for (@post), url: post_path do |f| %>
    <%= f.input :title %>
    <%= f.label :create_your_post %>
    <%= f.text_area :body, class: "form-control mt-2"%>
    <%= f.label :Image, class:"mt-3" %>
    <%= f.file_field :image %>
    <br>
    <%= f.button :submit, class:"btn-primary mt-3" %>
<% end %>
<div>

app/views/post/index.html.erb
<%= render "layouts/navbar" %>

<div class="container mt-5">
<table class="table">
  <thead>
    <tr>
      <th scope="col">No</th>
      <th scope="col">Judul</th>
      <th scope="col" colspan="3" class="text-center">Aksi</th>
    </tr>
  </thead>
  <tbody>
  <% @post.each_with_index do |post,index = 0| %>
  <% index += 1 %>
    <tr>
      <th scope="row"><%= index %></th>
      <td><%= post.title %></td>
      <td><%= link_to "Show", post_path(post), class:"badge bg-info text-dark" %></td>
      <td><%= link_to "Edit", edit_post_path(post), class:"badge bg-warning text-dark" %></td>
      <td><%= link_to "Delete", post_path(post), data: {
            turbo_method: :delete,
            turbo_confirm: 'Are you sure?'
            }, class:"badge bg-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/post/new.html.erb
<%= render "layouts/navbar" %>

<div class="container">
<%= simple_form_for (@post), url: post_index_path do |f| %>
    <%= f.input :title %>
    <%= f.label :create_your_post %>
    <%= f.text_area :body, class: "form-control mt-2"%>

    <%= f.label :Image, class:"mt-3" %>
    <%= f.file_field :image %>
    <br>
    <%= f.button :submit, class:"btn-primary mt-2" %>
<% end %>
<div>

app/views/post/show.html.erb
<%= render "layouts/navbar" %>

<div class="container mt-5">
    <div class="card">
    <div class="card-header text-center">
        <%= @post.title %>
    </div>
    <div class="card-body">
        <h5 class="card-title text-center"><%= @post.title %></h5>
        <%= image_tag(@post.image) %>
        <p class="card-text"><%= @post.body %></p>
     </div>
    </div>
</div>